# Generated by Django 2.2.4 on 2021-05-19 23:33

import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, validators=[apps.tasks.models.ValidarLongitudMinima])),
                ('lastname', models.CharField(max_length=45, validators=[apps.tasks.models.ValidarLongitudMinima])),
                ('email', models.CharField(max_length=50, validators=[apps.tasks.models.ValidarEmail])),
                ('password', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
