# Generated by Django 2.2.4 on 2021-05-27 00:39

import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(validators=[apps.tasks.models.ValidarFecha]),
        ),
    ]
