# Generated by Django 2.2.4 on 2021-05-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210531_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='users',
            field=models.ManyToManyField(related_name='users', to='tasks.User'),
        ),
    ]
