# Generated by Django 2.2.4 on 2021-05-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210531_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='tasks.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
